- name: Create network security group and rules
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: create nsg
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ nsg_name }}"
        location: "{{ location }}"
        rules:
          - name: Allow-ssh
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1000
            direction: Inbound

          - name: Allow-HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1010
            direction: Inbound
