- name: Create Azure Resource group using Ansible
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
