- name: create linux vm using ansible
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        network_interfaces: "{{ nic_name }}"
        os_disk_name: ansible-osdisk
        os_disk_caching: ReadWrite
        managed_disk_type: Standard_LRS
        image:
          publisher: Canonical 
          offer: 0001-com-ubuntu-server-jammy
          sku: 22_04-lts-gen2
          version: latest
