- name: create VNet and subnet using ansible
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefixes:
         - 10.0.0.0/16
        location: "{{ location }}"

    - name: create subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: 10.0.1.0/24
        virtual_network: "{{ vnet_name }}"

