---
- name: Deploy Streamlined Azure Infrastructure
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml

  tasks:
    - name: 1. Create Resource Group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: 2. Create Virtual Network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.0.0.0/16"
        location: "{{ location }}"

    - name: 3. Create Subnet (Separate Task)
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "10.0.1.0/24"
        virtual_network_name: "{{ vnet_name }}"

    - name: 4. Create Network Security Group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ nsg_name }}"
        rules:
          - name: AllowSSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 100
            direction: Inbound

    - name: 5. Create Public IP
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: ansible-pip
        location: "{{ location }}"
        allocation_method: Static
        sku: Standard

    - name: 6. Create NIC
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nic_name }}"
        location: "{{ location }}"
        security_group: "{{ nsg_name }}"
        subnet_name: "{{ subnet_name }}"
        virtual_network_name: "{{ vnet_name }}"
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: ansible-pip

    - name: 7. Create Virtual Machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        network_interfaces: "{{ nic_name }}"
        os_disk_name: ansible-osdisk
        os_disk_caching: ReadWrite
        managed_disk_type: Standard_LRS
        image:
          publisher: Canonical
          offer: 0001-com-ubuntu-server-jammy
          sku: 22_04-lts-gen2
          version: latest
