---
- name: Install and configure nginx
  hosts: webservers
  become: yes
  tasks:
    - name: 1. update apt cache and install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: 2. start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes
    - name: 3. create a Health check page
      copy:
        content: "healthy"
        dest: /var/www/html/health
    - name: 4. Test the health check locally
      uri:
        url: http://localhost/health
        status_code: 200
      register: result
    - name: 5. Display status
      debug:
        msg: "Nginx is up and health check is returning {{ result.status }}"
