---
- name: SRE Self-Healing - Restart Nginx
  hosts: webservers
  become: yes

  tasks:
    - name: 1. Check if Nginx is actually down
      ansible.builtin.uri:
        url: "http://localhost/health.html"
        status_code: 200
      register: web_status
      ignore_errors: yes

    - name: 2. Restart Nginx if health check failed
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: web_status.status != 200

    - name: 3. Verify the fix
      ansible.builtin.uri:
        url: "http://localhost/health.html"
        status_code: 200
      register: final_check
      until: final_check.status == 200
      retries: 3
      delay: 5
      when: web_status.status != 200
